version: '3.8'

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - express-app
    restart: always
